### ISSUE TITLE
Space between lines

### ISSUE THREAD

**Issue by arkhan** [datMaffin/monofoki#11]
Greetings, it is good to see that this project has the possibility of moving forward,
I only have one query in relation to the original source this is higher is this always going to be like this?

Original:
![2020-12-11_07-54](https://user-images.githubusercontent.com/3141865/101906426-ee9f3600-3b86-11eb-8ff1-c867fabc9d0a.png)

Fork:
![2020-12-11_07-55](https://user-images.githubusercontent.com/3141865/101906446-f65eda80-3b86-11eb-9e87-f9ee73b59f1a.png)

That is, it has more space between lines
Thank you

**Comment by datMaffin** [comment]
Sorry, totally overlooked your issue.
Thank you for trying my fork and giving feedback :D 

In general, I personally do prefer a less dense line height (Fork > Original).

As to why the line height is higher, I honestly do not know. The generation of the font file with FontForge seems to be different than the generation of the original font (the underlying values did not change; it is also possible that I do not understand which underlying value is used and may have changed it).

Depending on the terminal/program that is used it may be possible to change the lineheight.
E.g., Alacritty set number for `font.offset.y`, MacVim set via`:set linespace` and IntelliJ has a line height option as well.

**Comment by datMaffin** [comment]
I copied the height line metrics of the original mononoki font. The line height should now be identical.

(Name changed from MononokiFork to Monofoki)
