### ISSUE TITLE
Wrong glyph for U+0110 LATIN CAPITAL LETTER D WITH STROKE

### ISSUE THREAD

**Issue by dscorbett** [datMaffin/monofoki#18]
The glyph for U+0110 LATIN CAPITAL LETTER D WITH STROKE is wrong: it should look identical to the glyph for U+00D0 LATIN CAPITAL LETTER ETH.

**Comment by datMaffin** [comment]
Good find! Will close this issue after I regenerate the fonts (I currently just fixed it in the source files).
