### ISSUE TITLE
kitty terminal support

### ISSUE THREAD

**Issue by arkhan** [datMaffin/monofoki#27]
Cheers,
some letters do not draw well in kitty as you can see in the following image :
![image](https://user-images.githubusercontent.com/3141865/149006705-bcb79e48-82f6-4060-93f9-1a6825f23967.png)

Thank's

**Comment by datMaffin** [comment]
I am guessing that you mean that the g is cut off at the bottom(?)

Pretty sure that it would be possible to increase the line height. That is, effectively undoing #11 

In #11, you posted a screenshot of the original mononoki font. Does the problem of cut off letters now also exist with the original mononoki font?

I checked the kitty bugtracker, and there does not seem to be a recent change regarding line height rendering, though. What kitty version are you using?

**Comment by datMaffin** [comment]
Comparison of mononoki (left) and Monofoki (right):
![image](https://user-images.githubusercontent.com/29998721/149053760-a2727bae-f71b-47f2-966f-aed93c028cbd.png)

Looks like there is a possibility of moving all the lines down a bit to get (all) the letters to fit, though.

**Comment by arkhan** [comment]
> I am guessing that you mean that the g is cut off at the bottom(?)
> 
> Pretty sure that it would be possible to increase the line height. That is, effectively undoing #11
> 
the problem also occurs with mononoki
> In #11, you posted a screenshot of the original mononoki font. Does the problem of cut off letters now also exist with the original mononoki font?
> 
I'm using version 0.24.1
> I checked the kitty bugtracker, and there does not seem to be a recent change regarding line height rendering, though. What kitty version are you using?

for now I used alacritty again

**Comment by arkhan** [comment]
the problem was with kitty setup not with monofoki:
![image](https://user-images.githubusercontent.com/3141865/149219074-e4fadaaa-92b3-4084-a091-b1db08dff76d.png)

https://github.com/kovidgoyal/kitty/commit/941c55317293b060acc2675cd201d655f38f7b96#diff-fe51c7a3815fc2c4bfc3aac838ab5d83e01661d25b597865534c8df185f6935dR29
