### ISSUE TITLE
"(" and ")" should be mirrored

### ISSUE THREAD

**Issue by cmarincia** [datMaffin/monofoki#31]
This is from: https://github.com/madmalik/mononoki/issues/79

**Comment by datMaffin** [comment]
I am pretty sure that this is not an issue with Monofoki, because I use Fontforge, which seems to export symmetric parenthesis in .ttf.

In addition there are .otf files available that will be perfectly symmetrical because no conversion is necessary. (Mononoki only provides official .ttf that need to be converted. And the suboptimal conversion results in the issue of non mirrored parenthesis).

Can you give a screenshot showing that this is a problem with Monofoki?

**Comment by cmarincia** [comment]
The problem is still present at the .ttf fonts, the .otf fonts are perfect. I will switch to .otf.
TTF:
![image](https://user-images.githubusercontent.com/35623921/164996509-53c7f8f1-bbe5-4267-8035-cc58b7bceab1.png)
OTF:
![image](https://user-images.githubusercontent.com/35623921/164996571-c083f905-46f0-4782-9333-38c16e132ac3.png)

**Comment by datMaffin** [comment]
Interesting! So maybe my assumption about what went wrong is incorrect.

Hm also quite weird that I never encountered that issue; I believe I used the .ttf hinted on a regular resolution box on Linux (with the Gnome/XFCE Terminal)

I believe that I tried to reproduce this on Windows and was not able to reproduce it.

Will definitely try the ttf with Alacritty. 

I will very likely look into this issue in the next month; I am pretty busy for the next ~two weeks.

**Comment by cmarincia** [comment]
No pressure on this. The .otf work well.

**Comment by cmarincia** [comment]
Here it is: [Monofoki.zip](https://github.com/datMaffin/monofoki/files/8595046/Monofoki.zip)
For safety measures and also because I sent an archive:
Here are some details about it:
sha256:
```
c67950d09fa726bb5896fbe1c1a890c0ed3027fc954129c3fe03b5a6604e619f  Monofoki.zip
```
Virus total scan result(not a zip bomb or anything malicious):
https://www.virustotal.com/gui/file/c67950d09fa726bb5896fbe1c1a890c0ed3027fc954129c3fe03b5a6604e619f?nocache=1

**Comment by datMaffin** [comment]
I am not able to reproduce it:
Left is your screenshot, to the right how Monofoki NF looks like for me with size 8. Further to the right, how the otf looks like. And below, how Monofoki NF looks like in a dark theme (default alacritty colors).
![image](https://user-images.githubusercontent.com/29998721/166095721-2bd1c674-0b24-4971-8fad-3ad639af3ac7.png)

At this point I have the feeling that there is something wrong with alacrittys rendering on your platform(?) (I am on Linux)

**Comment by datMaffin** [comment]
For the next planned release, I anyways already changed the height metrics around to try and avoid #27.

Maybe this also fixes your issue?

If you want to try, I attached the export of the current master:
[next export.zip](https://github.com/datMaffin/monofoki/files/8596334/next.export.zip)

**Comment by datMaffin** [comment]
Cannot reproduce.

If anyone can provide more information about this issue, please reopen.
