### ISSUE TITLE
Add Ligature Support

### ISSUE THREAD

**Issue by carlomunguia** [datMaffin/monofoki#33]
Although Mononoki does not have ligatures, adding support for them here would be a great addition (especially for programmers in functional paradigms like Haskell or Elixir etc).

**Comment by datMaffin** [comment]
Sorry. I do not care for ligatures at all.

If you find a case where the default glyphs look badly aligned, however, like to improve them by ,e.g., move them or something like that.

I know that `:;` and the `-=<>~` do not align (e.g., `:=`) but I do like the current position more than have a compromise to align them.

In low resolution cases, the alignment can also go bad, but that is most of the time really hard to fix.

Of course it is always possible to fork and adapt this font however one wants. (I believe there is a person that is patching the Fira Code ligatures into this font)
