### ISSUE TITLE
Ligatures

### ISSUE THREAD

**Issue by 57r31** [datMaffin/monofoki#36]
Really nice code font @datMaffin ! Any chance to add ligatures to it? I'd try myself but need some directions

**Comment by datMaffin** [comment]
Hey,

Thanks for the compliment :)

You probably already found https://github.com/datMaffin/monofoki/issues/33 
The "upstream" font, also does not have any plans for it https://github.com/madmalik/mononoki/issues/29#issuecomment-1236322805 . So I think the best quick way would be patch some other ligatures into this font. 

Regarding giving some directions: I would guess that the regular ligature feature of fonts is used. Every font editor should support those. From my experience, getting warm with FontForge takes a long time, but it is free, and nowadays rarely crashes anymore.
But I would not include those ligatures in this version of the font, but feel free to fork.

**Comment by 57r31** [comment]
thanks @datMaffin 
https://www.glyphrstudio.com/v2/app/ this look really promising, think I'll take a try

**Comment by datMaffin** [comment]
The exported file that should be closest to what is saved in the `.sfd` files are the .otf files.
However, its still kind of sub-optimal (for example, I tell FontForge to unlink what it can). but should be enough to play with.

If you want, I can also export the `.sfd` files with FontForge to UFO (which I believe is the most popular format font editors support).

**Comment by 57r31** [comment]
actually [this thing](https://github.com/ToxicFrog/Ligaturizer) did the job perfectly
