### ISSUE TITLE
Ligatures?

### ISSUE THREAD

**Issue by Nabav** [datMaffin/monofoki#39]
See https://github.com/leopoldfajtak/liga_mononoki.

**Comment by datMaffin** [comment]
Sorry. Personally, I am not interested in ligatures.

See also:
- https://github.com/datMaffin/monofoki/issues/36
- https://github.com/datMaffin/monofoki/issues/33

**Comment by datMaffin** [comment]
Well, I randomly stumbled upon: https://github.com/57r31/monofoki
Maybe that would be already sufficient.

**Comment by Nabav** [comment]
Thanks for that link. Great work.
